export const PRICING_DATA = {
    'hotel-booking': [
        {
            name: 'Starter',
            tagline: 'Essential tools for small hotels & guest houses',
            priceMonthly: 45,
            priceAnnually: 36,
            cta: 'Get Started',
            highlight: false,
            features: [
                'Room booking system',
                'Basic guest management',
                'Single property support',
                'Email confirmations',
                'Up to 2 users',
            ],
        },
        {
            name: 'Professional',
            tagline: 'Advanced features for growing hospitality businesses',
            priceMonthly: 85,
            priceAnnually: 68,
            cta: 'Request Demo',
            highlight: false,
            features: [
                'Multi-property support',
                'Advanced guest profiles',
                'Availability tracking',
                'Payment integration',
                'Up to 10 users',
            ],
        },
        {
            name: 'Premium',
            tagline: 'Complete automation for large hotel chains',
            priceMonthly: 120,
            priceAnnually: 96,
            cta: 'Request Demo',
            highlight: true,
            features: [
                'All Professional features',
                'Real-time inventory sync',
                'Channel manager integration',
                'Housekeeping management',
                'Unlimited users',
                'Priority support',
            ],
        },
        {
            name: 'Enterprise',
            tagline: 'Tailor-made solutions for global organizations',
            custom: true,
            cta: 'Contact Sales',
            highlight: false,
            features: [
                'Custom workflows',
                'Private API & webhooks',
                'Advanced reporting',
                'Dedicated account manager',
                'Custom onboarding',
            ],
        },
    ],
    'travel-management': [
        {
            name: 'Starter',
            tagline: 'Digitize your travel agency operations',
            priceMonthly: 50,
            priceAnnually: 40,
            cta: 'Get Started',
            highlight: false,
            features: [
                'Basic system access',
                'Itinerary builder',
                'CRM basics',
                '3 users included',
            ],
        },
        {
            name: 'Professional',
            tagline: 'Full visibility for scaling agencies',
            priceMonthly: 95,
            priceAnnually: 76,
            cta: 'Request Demo',
            highlight: false,
            features: [
                'CRM + Booking + Finance',
                'Multi-user management',
                'Automated invoicing',
                'Supplier database',
                '10 users included',
            ],
        },
        {
            name: 'Premium',
            tagline: 'The complete travel operations hub',
            priceMonthly: 140,
            priceAnnually: 112,
            cta: 'Request Demo',
            highlight: true,
            features: [
                'All Professional features',
                'Advanced reporting',
                'Multi-brand support',
                'Automated workflows',
                'Unlimited users',
                'White-label portal',
            ],
        },
        {
            name: 'Enterprise',
            tagline: 'Global solutions for enterprise travel',
            custom: true,
            cta: 'Contact Sales',
            highlight: false,
            features: [
                'Global distribution sync',
                'Private hosting options',
                'Custom integrations',
                'SLA & 24/7 support',
            ],
        },
    ],
    'accounting': [
        {
            name: 'Starter',
            tagline: 'Clear finances for small businesses',
            priceMonthly: 35,
            priceAnnually: 28,
            cta: 'Get Started',
            highlight: false,
            features: [
                'Invoices & payments',
                'Expense tracking',
                '1 user included',
                'Standard reports',
            ],
        },
        {
            name: 'Professional',
            tagline: 'Complete accounting for travel teams',
            priceMonthly: 75,
            priceAnnually: 60,
            cta: 'Request Demo',
            highlight: false,
            features: [
                'Financial reports',
                'Tax automation',
                'Multi-currency support',
                '5 users included',
                'Bank reconciliation',
            ],
        },
        {
            name: 'Premium',
            tagline: 'Intelligent financial management',
            priceMonthly: 110,
            priceAnnually: 88,
            cta: 'Request Demo',
            highlight: true,
            features: [
                'All Professional features',
                'Advanced analytics',
                'Audit logs',
                'Automated reconciliation',
                'Unlimited users',
                'Priority support',
            ],
        },
        {
            name: 'Enterprise',
            tagline: 'Custom ERP & financial workflows',
            custom: true,
            cta: 'Contact Sales',
            highlight: false,
            features: [
                'Enterprise ERP sync',
                'Custom accounting rules',
                'Dedicated accountant',
                'Full API access',
            ],
        },
    ],
    'fleet-operations': [
        {
            name: 'Starter',
            tagline: 'Basic tracking for small fleets',
            priceMonthly: 40,
            priceAnnually: 32,
            cta: 'Get Started',
            highlight: false,
            features: [
                'Fleet tracking (basic)',
                'Driver list',
                'Trip logs',
                'Up to 5 vehicles',
            ],
        },
        {
            name: 'Professional',
            tagline: 'Optimized operations for growing fleets',
            priceMonthly: 80,
            priceAnnually: 64,
            cta: 'Request Demo',
            highlight: false,
            features: [
                'Real-time fleet tracking',
                'Driver assignment',
                'Resource planning',
                'Maintenance alerts',
                'Up to 20 vehicles',
            ],
        },
        {
            name: 'Premium',
            tagline: 'Maximum efficiency for large fleets',
            priceMonthly: 130,
            priceAnnually: 104,
            cta: 'Request Demo',
            highlight: true,
            features: [
                'All Professional features',
                'Fuel management',
                'Route optimization',
                'Compliance tracking',
                'Unlimited vehicles',
                'Predictive maintenance',
            ],
        },
        {
            name: 'Enterprise',
            tagline: 'Custom logistics & telematics',
            custom: true,
            cta: 'Contact Sales',
            highlight: false,
            features: [
                'Telematics integration',
                'Custom dispatch rules',
                'Advanced API access',
                'White-label options',
            ],
        },
    ],
    'tour-guide': [
        {
            name: 'Starter',
            tagline: 'Simple tools for independent guides',
            priceMonthly: 25,
            priceAnnually: 20,
            cta: 'Get Started',
            highlight: false,
            features: [
                'Daily schedule',
                'Tour details',
                'Basic client list',
                'Standard support',
            ],
        },
        {
            name: 'Professional',
            tagline: 'Seamless coordination for tour teams',
            priceMonthly: 55,
            priceAnnually: 44,
            cta: 'Request Demo',
            highlight: false,
            features: [
                'Real-time updates',
                'Guide assignment',
                'Resource tracking',
                'Client feedback system',
                'Up to 5 guides',
            ],
        },
        {
            name: 'Premium',
            tagline: 'The ultimate tour management app',
            priceMonthly: 85,
            priceAnnually: 68,
            cta: 'Request Demo',
            highlight: true,
            features: [
                'All Professional features',
                'Interactive maps',
                'Multi-language support',
                'Automated notifications',
                'Unlimited guides',
                'Offline mode',
            ],
        },
        {
            name: 'Enterprise',
            tagline: 'Custom white-label guide solutions',
            custom: true,
            cta: 'Contact Sales',
            highlight: false,
            features: [
                'Custom app branding',
                'Deep system integration',
                'Enterprise reporting',
                'Dedicated support',
            ],
        },
    ],
    'driver-app': [
        {
            name: 'Starter',
            tagline: 'Essential tools for drivers',
            priceMonthly: 20,
            priceAnnually: 16,
            cta: 'Get Started',
            highlight: false,
            features: [
                'Trip assignments',
                'Route tracking',
                'Basic navigation',
                'Status updates',
            ],
        },
        {
            name: 'Professional',
            tagline: 'Advanced navigation & tracking',
            priceMonthly: 45,
            priceAnnually: 36,
            cta: 'Request Demo',
            highlight: false,
            features: [
                'Navigation support (Pro)',
                'Expense logging',
                'Chat with dispatch',
                'Digital signatures',
                'Up to 10 drivers',
            ],
        },
        {
            name: 'Premium',
            tagline: 'The driver performance hub',
            priceMonthly: 75,
            priceAnnually: 60,
            cta: 'Request Demo',
            highlight: true,
            features: [
                'All Professional features',
                'Performance analytics',
                'Auto-dispatch sync',
                'Document scanner',
                'Unlimited drivers',
                'Priority support',
            ],
        },
        {
            name: 'Enterprise',
            tagline: 'Tailored mobility solutions',
            custom: true,
            cta: 'Contact Sales',
            highlight: false,
            features: [
                'Hardware integration',
                'Custom safety rules',
                'Fleet management sync',
                'Enterprise security',
            ],
        },
    ],
    'hr-app': [
        {
            name: 'Starter',
            tagline: 'Basic HR for small teams',
            priceMonthly: 30,
            priceAnnually: 24,
            cta: 'Get Started',
            highlight: false,
            features: [
                'Employee management',
                'Attendance tracking',
                'Basic profiles',
                'Up to 10 employees',
            ],
        },
        {
            name: 'Professional',
            tagline: 'Complete workforce management',
            priceMonthly: 65,
            priceAnnually: 52,
            cta: 'Request Demo',
            highlight: false,
            features: [
                'Payroll automation',
                'Leave management',
                'Document storage',
                'Performance reviews',
                'Up to 50 employees',
            ],
        },
        {
            name: 'Premium',
            tagline: 'Strategic human resources hub',
            priceMonthly: 95,
            priceAnnually: 76,
            cta: 'Request Demo',
            highlight: true,
            features: [
                'All Professional features',
                'Advanced reporting',
                'Recruitment tools',
                'Benefit administration',
                'Unlimited employees',
                'Priority support',
            ],
        },
        {
            name: 'Enterprise',
            tagline: 'Custom global HR solutions',
            custom: true,
            cta: 'Contact Sales',
            highlight: false,
            features: [
                'Global payroll sync',
                'Custom compliance rules',
                'LMS integration',
                'Dedicated HR consultant',
            ],
        },
    ],
    'contract-management': [
        {
            name: 'Starter',
            tagline: 'Organize your partner agreements',
            priceMonthly: 40,
            priceAnnually: 32,
            cta: 'Get Started',
            highlight: false,
            features: [
                'Contract creation (Basic)',
                'Partner agreements',
                'Document tracking',
                'Up to 50 contracts',
            ],
        },
        {
            name: 'Professional',
            tagline: 'Streamlined contract lifecycle',
            priceMonthly: 85,
            priceAnnually: 68,
            cta: 'Request Demo',
            highlight: false,
            features: [
                'Digital signatures',
                'Renewal alerts',
                'Version control',
                'Approval workflows',
                'Up to 200 contracts',
            ],
        },
        {
            name: 'Premium',
            tagline: 'The ultimate legal operations hub',
            priceMonthly: 125,
            priceAnnually: 100,
            cta: 'Request Demo',
            highlight: true,
            features: [
                'All Professional features',
                'AI contract analysis',
                'Compliance auditing',
                'Bulk actions',
                'Unlimited contracts',
                'Priority support',
            ],
        },
        {
            name: 'Enterprise',
            tagline: 'Custom legal & compliance workflows',
            custom: true,
            cta: 'Contact Sales',
            highlight: false,
            features: [
                'Single Sign-On (SSO)',
                'Custom legal templates',
                'Audit-ready reporting',
                'Dedicated legal engineer',
            ],
        },
    ],
    'inbox-master': [
        {
            name: 'Starter',
            tagline: 'Essencial para equipas que começam a centralizar comunicações',
            priceMonthly: 49,
            priceAnnually: 41,
            cta: 'Get Started',
            highlight: false,
            features: [
                'Email & Task Management',
                'Gestão de Anexos Centralizada',
                'Comentários Internos & Reminders and Custom Properties',
                'Notificações Desktop Push',
                'Segurança 2FA (Dois Fatores)',
                'Logs de Auditoria de Acesso',
                'Backup de Dados Diário',
                'Up to 1 brand · Webhooks: 3.000/mês',
                'Up to 5 Templates de Resposta Rápida',
                'History Limit: 6 months · Storage: 25 GB · Up to 3 users',
            ],
        },
        {
            name: 'Essencial',
            tagline: 'Chat omnicanal e automação para equipas em crescimento',
            priceMonthly: 129,
            priceAnnually: 108,
            cta: 'Request Demo',
            highlight: false,
            features: [
                'Everything included in STARTER and:',
                'All-in-one Chat Integration',
                'Filtros de Mensagens Avançados',
                'Filtro Anti-Spam Inteligente',
                'Integração com sistemas da Bu Marca',
                'Atribuição Automática de tickets',
                'Aplicativo Chat IC (iOS/Android)',
                'Up to 1 brand · Webhooks: 100.000/mês',
                'Up to 25 Templates de Resposta Rápida',
                'History Limit: 2 years · Storage: 100 GB · Up to 10 users',
            ],
        },
        {
            name: 'Premium',
            tagline: 'IA, analytics e multi-empresa para operações avançadas',
            priceMonthly: 299,
            priceAnnually: 249,
            cta: 'Request Demo',
            highlight: true,
            features: [
                'Everything included in ESSENCIAL and:',
                'Exportação de Dados (CSV/PDF)',
                'Relatórios de Performance de Equipa',
                'Sondagens de Satisfação (CSAT)',
                'Sugestão de Respostas por IA',
                'Análise de Sentimento (IA)',
                'Resumo de Conversas Longas (IA)',
                'Tradução Automática (40+ línguas)',
                'Multi-Empresa (Up to 2 brands) · Webhooks: Ilimitado',
                'History Limit: 10 years · Storage: 200 GB · Up to 50 users',
            ],
        },
        {
            name: 'Enterprise',
            tagline: 'Solução totalmente personalizada para grandes organizações',
            custom: true,
            cta: 'Contact Sales',
            highlight: false,
            features: [
                'Everything included in PREMIUM and:',
                'Advanced Custom Fields',
                'Team Contact Manager',
                'Zapier & Data Export',
                'Unlimited History',
                'Priority Support',
                'White Label (Marca Própria)',
                'SLA Rules',
                'Unlimited brands · Unlimited webhooks · Unlimited users',
            ],
        },
    ],
    'hr-pulse': [
        {
            name: 'Starter',
            tagline: 'Gestão de pessoas essencial para pequenas equipas',
            priceMonthly: 79,
            priceAnnually: 66,
            cta: 'Get Started',
            highlight: false,
            features: [
                'Criação de Links de Vagas',
                'Gestão de Candidatos (ATS)',
                'Gestão de Documentos Pessoais',
                'Portal do Colaborador (Self-Service)',
                'Agendamento de Entrevistas',
                'Consulta Horas & Consulta Faltas',
                'Logs Auditoria Básico',
                'Distribuição de Recibos de Vencimento',
                'Gestão Ativos & Entrevistas Saída',
                'Gestão de Assiduidade & Horários',
                'Pedidos de Férias e Ausências',
                'Gestão de Baixas Médicas',
                'Processamento de Salários Manual',
                'Up to 1 brand · 3 users · Webhooks: 3.000/mês · Storage: 25 GB · Histórico: 6 meses',
            ],
        },
        {
            name: 'Essencial',
            tagline: 'Automação de RH e app para colaboradores em crescimento',
            priceMonthly: 129,
            priceAnnually: 108,
            cta: 'Request Demo',
            highlight: false,
            features: [
                'Inquéritos de Clima Organizacional',
                'Alertas de Renovação/Fim de Contrato',
                'App Funcionário',
                'Gestão Férias & Pedidos via App',
                'Gestão Documentos da Empresa',
                'Alertas Docs & Reembolsos',
                'Registo de Medidas Disciplinares',
                'Medicina Trabalho',
                'Gestão Escalas',
                'Gestão de Horas Extraordinárias',
                'Planeamento de Escalas e Turnos',
                'Cálculo de Impostos e Retenções',
                'Processamento de Salários Automático',
                'Up to 1 brand · 10 users · Webhooks: 100.000/mês · Storage: 100 GB · Histórico: 2 anos',
            ],
        },
        {
            name: 'Premium',
            tagline: 'IA, avaliações 360° e conectores ERP para RH avançado',
            priceMonthly: 299,
            priceAnnually: 249,
            cta: 'Request Demo',
            highlight: true,
            features: [
                'Triagem Automática de CVs por IA',
                'Testes de Avaliação Online',
                'Onboarding Digital de Empregados',
                'Gerador de Contratos Dinâmicos',
                'Assinatura Digital Integrada',
                'LMS Treino & Folha Salários',
                'Avaliação de Desempenho (360°)',
                'Logs de Auditoria Completo',
                'Certificações & Gestão Benefícios',
                'Conectores ERP',
                'Reports Estatísticos',
                'Reembolso de Despesas e Viagens',
                'Processamento de Salários (IA-Optimizado)',
                'Multi-Empresa (2 brands) · 50 users · Webhooks: Ilimitado · Storage: 200 GB · Histórico: 10 anos',
            ],
        },
        {
            name: 'Enterprise',
            tagline: 'Plataforma de RH totalmente personalizada e escalável',
            custom: true,
            cta: 'Contact Sales',
            highlight: false,
            features: [
                'Picagem Ponto & Biometria',
                'Organograma da Empresa Dinâmico',
                'Segurança Social',
                'Integração com Máquinas Biométricas',
                'Conectores API para ERPs',
                'Integração com Segurança Social',
                'Gestão de Objetivos e OKRs',
                'Sistema de Formação (LMS)',
                'Relatórios Estatísticos de RH',
                'Processamento de Salários Custom',
                'Unlimited brands & users · Webhooks: Ilimitado · Storage: Ilimitado',
            ],
        },
    ],
    'all-products': [
        {
            name: 'Starter',
            tagline: 'Foundational tools for any business',
            priceMonthly: 35,
            priceAnnually: 28,
            cta: 'Get Started',
            highlight: false,
            features: [
                'Core system access',
                'Basic reporting',
                'Email support',
                'Up to 3 users',
            ],
        },
        {
            name: 'Professional',
            tagline: 'The choice for growing companies',
            priceMonthly: 75,
            priceAnnually: 60,
            cta: 'Request Demo',
            highlight: false,
            features: [
                'Advanced features',
                'Priority workflows',
                'Multi-user tools',
                'Up to 10 users',
            ],
        },
        {
            name: 'Premium',
            tagline: 'Complete automation & scale',
            priceMonthly: 110,
            priceAnnually: 88,
            cta: 'Request Demo',
            highlight: true,
            features: [
                'Full platform access',
                'Predictive analytics',
                'Unlimited users',
                '24/7 Priority support',
            ],
        },
        {
            name: 'Enterprise',
            tagline: 'Custom tailored platform',
            custom: true,
            cta: 'Contact Sales',
            highlight: false,
            features: [
                'White-label options',
                'Custom development',
                'Dedicated infrastructure',
                'Personalized training',
            ],
        },
    ],
};
