export const PRICING_DATA = {
    'hotel-booking': [
        {
            name: 'Starter',
            tagline: 'Essential tools for small hotels & guest houses',
            priceMonthly: 45,
            priceAnnually: 36,
            cta: 'Get Started',
            highlight: false,
            features: [
                'Room booking system',
                'Basic guest management',
                'Single property support',
                'Email confirmations',
                'Up to 2 users',
            ],
        },
        {
            name: 'Professional',
            tagline: 'Advanced features for growing hospitality businesses',
            priceMonthly: 85,
            priceAnnually: 68,
            cta: 'Request Demo',
            highlight: false,
            features: [
                'Multi-property support',
                'Advanced guest profiles',
                'Availability tracking',
                'Payment integration',
                'Up to 10 users',
            ],
        },
        {
            name: 'Premium',
            tagline: 'Complete automation for large hotel chains',
            priceMonthly: 120,
            priceAnnually: 96,
            cta: 'Request Demo',
            highlight: true,
            features: [
                'All Professional features',
                'Real-time inventory sync',
                'Channel manager integration',
                'Housekeeping management',
                'Unlimited users',
                'Priority support',
            ],
        },
        {
            name: 'Enterprise',
            tagline: 'Tailor-made solutions for global organizations',
            custom: true,
            cta: 'Contact Sales',
            highlight: false,
            features: [
                'Custom workflows',
                'Private API & webhooks',
                'Advanced reporting',
                'Dedicated account manager',
                'Custom onboarding',
            ],
        },
    ],
    'travel-management': [
        {
            name: 'Starter',
            tagline: 'Digitize your travel agency operations',
            priceMonthly: 50,
            priceAnnually: 40,
            cta: 'Get Started',
            highlight: false,
            features: [
                'Basic system access',
                'Itinerary builder',
                'CRM basics',
                '3 users included',
            ],
        },
        {
            name: 'Professional',
            tagline: 'Full visibility for scaling agencies',
            priceMonthly: 95,
            priceAnnually: 76,
            cta: 'Request Demo',
            highlight: false,
            features: [
                'CRM + Booking + Finance',
                'Multi-user management',
                'Automated invoicing',
                'Supplier database',
                '10 users included',
            ],
        },
        {
            name: 'Premium',
            tagline: 'The complete travel operations hub',
            priceMonthly: 140,
            priceAnnually: 112,
            cta: 'Request Demo',
            highlight: true,
            features: [
                'All Professional features',
                'Advanced reporting',
                'Multi-brand support',
                'Automated workflows',
                'Unlimited users',
                'White-label portal',
            ],
        },
        {
            name: 'Enterprise',
            tagline: 'Global solutions for enterprise travel',
            custom: true,
            cta: 'Contact Sales',
            highlight: false,
            features: [
                'Global distribution sync',
                'Private hosting options',
                'Custom integrations',
                'SLA & 24/7 support',
            ],
        },
    ],
    'accounting': [
        {
            name: 'Starter',
            tagline: 'Clear finances for small businesses',
            priceMonthly: 35,
            priceAnnually: 28,
            cta: 'Get Started',
            highlight: false,
            features: [
                'Invoices & payments',
                'Expense tracking',
                '1 user included',
                'Standard reports',
            ],
        },
        {
            name: 'Professional',
            tagline: 'Complete accounting for travel teams',
            priceMonthly: 75,
            priceAnnually: 60,
            cta: 'Request Demo',
            highlight: false,
            features: [
                'Financial reports',
                'Tax automation',
                'Multi-currency support',
                '5 users included',
                'Bank reconciliation',
            ],
        },
        {
            name: 'Premium',
            tagline: 'Intelligent financial management',
            priceMonthly: 110,
            priceAnnually: 88,
            cta: 'Request Demo',
            highlight: true,
            features: [
                'All Professional features',
                'Advanced analytics',
                'Audit logs',
                'Automated reconciliation',
                'Unlimited users',
                'Priority support',
            ],
        },
        {
            name: 'Enterprise',
            tagline: 'Custom ERP & financial workflows',
            custom: true,
            cta: 'Contact Sales',
            highlight: false,
            features: [
                'Enterprise ERP sync',
                'Custom accounting rules',
                'Dedicated accountant',
                'Full API access',
            ],
        },
    ],
    'fleet-operations': [
        {
            name: 'Starter',
            tagline: 'Basic tracking for small fleets',
            priceMonthly: 40,
            priceAnnually: 32,
            cta: 'Get Started',
            highlight: false,
            features: [
                'Fleet tracking (basic)',
                'Driver list',
                'Trip logs',
                'Up to 5 vehicles',
            ],
        },
        {
            name: 'Professional',
            tagline: 'Optimized operations for growing fleets',
            priceMonthly: 80,
            priceAnnually: 64,
            cta: 'Request Demo',
            highlight: false,
            features: [
                'Real-time fleet tracking',
                'Driver assignment',
                'Resource planning',
                'Maintenance alerts',
                'Up to 20 vehicles',
            ],
        },
        {
            name: 'Premium',
            tagline: 'Maximum efficiency for large fleets',
            priceMonthly: 130,
            priceAnnually: 104,
            cta: 'Request Demo',
            highlight: true,
            features: [
                'All Professional features',
                'Fuel management',
                'Route optimization',
                'Compliance tracking',
                'Unlimited vehicles',
                'Predictive maintenance',
            ],
        },
        {
            name: 'Enterprise',
            tagline: 'Custom logistics & telematics',
            custom: true,
            cta: 'Contact Sales',
            highlight: false,
            features: [
                'Telematics integration',
                'Custom dispatch rules',
                'Advanced API access',
                'White-label options',
            ],
        },
    ],
    'tour-guide': [
        {
            name: 'Starter',
            tagline: 'Simple tools for independent guides',
            priceMonthly: 25,
            priceAnnually: 20,
            cta: 'Get Started',
            highlight: false,
            features: [
                'Daily schedule',
                'Tour details',
                'Basic client list',
                'Standard support',
            ],
        },
        {
            name: 'Professional',
            tagline: 'Seamless coordination for tour teams',
            priceMonthly: 55,
            priceAnnually: 44,
            cta: 'Request Demo',
            highlight: false,
            features: [
                'Real-time updates',
                'Guide assignment',
                'Resource tracking',
                'Client feedback system',
                'Up to 5 guides',
            ],
        },
        {
            name: 'Premium',
            tagline: 'The ultimate tour management app',
            priceMonthly: 85,
            priceAnnually: 68,
            cta: 'Request Demo',
            highlight: true,
            features: [
                'All Professional features',
                'Interactive maps',
                'Multi-language support',
                'Automated notifications',
                'Unlimited guides',
                'Offline mode',
            ],
        },
        {
            name: 'Enterprise',
            tagline: 'Custom white-label guide solutions',
            custom: true,
            cta: 'Contact Sales',
            highlight: false,
            features: [
                'Custom app branding',
                'Deep system integration',
                'Enterprise reporting',
                'Dedicated support',
            ],
        },
    ],
    'driver-app': [
        {
            name: 'Starter',
            tagline: 'Essential tools for drivers',
            priceMonthly: 20,
            priceAnnually: 16,
            cta: 'Get Started',
            highlight: false,
            features: [
                'Trip assignments',
                'Route tracking',
                'Basic navigation',
                'Status updates',
            ],
        },
        {
            name: 'Professional',
            tagline: 'Advanced navigation & tracking',
            priceMonthly: 45,
            priceAnnually: 36,
            cta: 'Request Demo',
            highlight: false,
            features: [
                'Navigation support (Pro)',
                'Expense logging',
                'Chat with dispatch',
                'Digital signatures',
                'Up to 10 drivers',
            ],
        },
        {
            name: 'Premium',
            tagline: 'The driver performance hub',
            priceMonthly: 75,
            priceAnnually: 60,
            cta: 'Request Demo',
            highlight: true,
            features: [
                'All Professional features',
                'Performance analytics',
                'Auto-dispatch sync',
                'Document scanner',
                'Unlimited drivers',
                'Priority support',
            ],
        },
        {
            name: 'Enterprise',
            tagline: 'Tailored mobility solutions',
            custom: true,
            cta: 'Contact Sales',
            highlight: false,
            features: [
                'Hardware integration',
                'Custom safety rules',
                'Fleet management sync',
                'Enterprise security',
            ],
        },
    ],
    'hr-app': [
        {
            name: 'Starter',
            tagline: 'Basic HR for small teams',
            priceMonthly: 30,
            priceAnnually: 24,
            cta: 'Get Started',
            highlight: false,
            features: [
                'Employee management',
                'Attendance tracking',
                'Basic profiles',
                'Up to 10 employees',
            ],
        },
        {
            name: 'Professional',
            tagline: 'Complete workforce management',
            priceMonthly: 65,
            priceAnnually: 52,
            cta: 'Request Demo',
            highlight: false,
            features: [
                'Payroll automation',
                'Leave management',
                'Document storage',
                'Performance reviews',
                'Up to 50 employees',
            ],
        },
        {
            name: 'Premium',
            tagline: 'Strategic human resources hub',
            priceMonthly: 95,
            priceAnnually: 76,
            cta: 'Request Demo',
            highlight: true,
            features: [
                'All Professional features',
                'Advanced reporting',
                'Recruitment tools',
                'Benefit administration',
                'Unlimited employees',
                'Priority support',
            ],
        },
        {
            name: 'Enterprise',
            tagline: 'Custom global HR solutions',
            custom: true,
            cta: 'Contact Sales',
            highlight: false,
            features: [
                'Global payroll sync',
                'Custom compliance rules',
                'LMS integration',
                'Dedicated HR consultant',
            ],
        },
    ],
    'contract-management': [
        {
            name: 'Starter',
            tagline: 'Organize your partner agreements',
            priceMonthly: 40,
            priceAnnually: 32,
            cta: 'Get Started',
            highlight: false,
            features: [
                'Contract creation (Basic)',
                'Partner agreements',
                'Document tracking',
                'Up to 50 contracts',
            ],
        },
        {
            name: 'Professional',
            tagline: 'Streamlined contract lifecycle',
            priceMonthly: 85,
            priceAnnually: 68,
            cta: 'Request Demo',
            highlight: false,
            features: [
                'Digital signatures',
                'Renewal alerts',
                'Version control',
                'Approval workflows',
                'Up to 200 contracts',
            ],
        },
        {
            name: 'Premium',
            tagline: 'The ultimate legal operations hub',
            priceMonthly: 125,
            priceAnnually: 100,
            cta: 'Request Demo',
            highlight: true,
            features: [
                'All Professional features',
                'AI contract analysis',
                'Compliance auditing',
                'Bulk actions',
                'Unlimited contracts',
                'Priority support',
            ],
        },
        {
            name: 'Enterprise',
            tagline: 'Custom legal & compliance workflows',
            custom: true,
            cta: 'Contact Sales',
            highlight: false,
            features: [
                'Single Sign-On (SSO)',
                'Custom legal templates',
                'Audit-ready reporting',
                'Dedicated legal engineer',
            ],
        },
    ],
    'inbox-master': [
        {
            name: 'Starter',
            tagline: 'Essential tools for teams starting to centralize communications',
            priceMonthly: 49,
            priceAnnually: 41,
            cta: 'Get Started',
            highlight: false,
            features: [
                'Unified Email & Task Inbox',
                'Centralized Attachment Management',
                'Internal Comments & @team Mentions in Real Time',
                'Smart Reminders and Custom Fields',
                'Instant Desktop Push Notifications',
                'Enterprise-Grade Security with 2FA',
                'Access Audit Logs and Activity Tracking',
                'Secure Daily Automatic Backups',
                'Up to 1 brand · Webhooks: 3,000/month',
                'Up to 5 Templates de Resposta Rápidas',
                'History Limit: 6 months · Storage: 25 GB · Up to 3 users',
            ],
        },
        {
            name: 'Essencial',
            tagline: 'Omnichannel inbox and automation for growing teams',
            priceMonthly: 129,
            priceAnnually: 108,
            cta: 'Request Demo',
            highlight: false,
            features: [
                'Everything included in STARTER and:',
                'Unified Inbox: Gmail, WhatsApp, Instagram & more',
                'Advanced Smart Message Filters',
                'Intelligent Anti-Spam System',
                'Integration with Your Brand Systems',
                'Automatic Ticket Assignment to Team Members',
                'IC Chat Mobile App (iOS & Android) for On-the-Go',
                'Up to 1 brand · Webhooks: 100,000/month',
                'Up to 25 Templates de Resposta Rápidas',
                'History Limit: 2 years · Storage: 100 GB · Up to 10 users',
            ],
        },
        {
            name: 'Premium',
            tagline: 'AI, analytics and multi-brand for advanced operations',
            priceMonthly: 299,
            priceAnnually: 249,
            cta: 'Request Demo',
            highlight: true,
            features: [
                'Everything included in ESSENCIAL and:',
                'Data Export in CSV & PDF',
                'Full Team Performance Reporting',
                'Built-in CSAT (Customer Satisfaction Tracking)',
                'AI-Powered Response Suggestions',
                'Sentiment Analysis Across All Conversations',
                'Smart Summaries of Long Conversations',
                'Automatic Translation in 40+ Languages',
                'Multi-Empresa (Up to 2 brands) · Unlimited Webhooks',
                'History Limit: 10 years · Storage: 200 GB · Up to 50 users',
            ],
        },
        {
            name: 'Enterprise',
            tagline: 'Fully custom solution for large-scale organizations',
            custom: true,
            cta: 'Contact Sales',
            highlight: false,
            features: [
                'Everything included in PREMIUM and:',
                'Advanced Custom Fields for Any Workflow',
                'Full Team Contact Management System',
                'Zapier Integration & Advanced Data Export',
                'Unlimited Conversation History',
                'Priority Support with Fast Response Times',
                'White-Label Platform with Your Own Branding',
                'SLA Rules for Professional Service-Level Management',
                'Unlimited brands · Unlimited webhooks · Unlimited users',
            ],
        },
    ],
    'hr-pulse': [
        {
            name: 'Starter',
            tagline: 'Essential HR tools for small teams getting started',
            priceMonthly: 79,
            priceAnnually: 66,
            cta: 'Get Started',
            highlight: false,
            features: [
                'Job Posting & Career Link Management',
                'Applicant Tracking System (ATS)',
                'Candidate Management',
                'Interview Scheduling',
                'Employee Document Management',
                'Employee Self-Service Portal',
                'Time & Attendance Tracking',
                'Absence & Leave Requests',
                'Basic Audit Logs',
                'Payslip Distribution',
                'Company Asset Management',
                'Exit Interviews',
                'Shift Scheduling',
                'Medical Leave Management',
                'Processamento de Salários Manual',
                'Up to 1 brand · Webhooks: 3,000/month',
                'Up to 5 Templates de Resposta Rápidas',
                'History Limit: 6 months · Storage: 25 GB · Up to 3 users',
            ],
        },
        {
            name: 'Essencial',
            tagline: 'HR automation and employee app for growing teams',
            priceMonthly: 129,
            priceAnnually: 108,
            cta: 'Request Demo',
            highlight: false,
            features: [
                'Everything included in STARTER and:',
                'Contract Renewal & Expiration Alerts',
                'Employee Mobile App',
                'Leave Management System',
                'Employee Requests via App',
                'Company Document Management',
                'Document Expiry Alerts',
                'Expense Reimbursements',
                'Disciplinary Records Management',
                'Occupational Health Tracking',
                'Workforce Scheduling Management',
                'Overtime Management',
                'Tax Calculation & Withholding',
                'Employee Climate & Engagement Surveys',
                'Processamento de Salários Automático',
                'Up to 1 brand · Webhooks: 100,000/month',
                'Up to 25 Templates de Resposta Rápidas',
                'History Limit: 2 years · Storage: 100 GB · Up to 10 users',
            ],
        },
        {
            name: 'Premium',
            tagline: 'AI, 360° reviews and ERP connectors for advanced HR',
            priceMonthly: 299,
            priceAnnually: 249,
            cta: 'Request Demo',
            highlight: true,
            features: [
                'Everything included in ESSENCIAL and:',
                'AI-Powered CV Screening',
                'Online Candidate Assessments',
                'Digital Employee Onboarding',
                'Dynamic Contract Generator',
                'Integrated Digital Signature',
                'Learning Management System (LMS)',
                'Payroll Management System',
                '360° Performance Reviews',
                'Full Audit Logs (Advanced)',
                'Certifications Management',
                'Benefits Management',
                'ERP Connectors',
                'Advanced HR Reporting',
                'Processamento de Salários (IA-Optimizado)',
                'Multi-Empresa (Up to 2 brands) · Unlimited Webhooks',
                'History Limit: 10 years · Storage: 200 GB · Up to 50 users',
            ],
        },
        {
            name: 'Enterprise',
            tagline: 'Fully custom and scalable HR platform for large organizations',
            custom: true,
            cta: 'Contact Sales',
            highlight: false,
            features: [
                'Everything included in PREMIUM and:',
                'Biometric Time Tracking',
                'Dynamic Organizational Chart',
                'Social Security Integration',
                'Biometric Device Integration',
                'ERP API Integrations',
                'HR & Workforce Analytics',
                'OKRs & Goal Management System',
                'Training & Development System',
                'Advanced Statistical HR Reports',
                'Custom Payroll Processing',
                'Unlimited brands · Unlimited webhooks · Unlimited users',
            ],
        },
    ],
    'link-trip': [
        {
            name: 'Starter',
            tagline: 'Essential trip building tools for growing agencies',
            priceMonthly: 99,
            priceAnnually: 83,
            cta: 'Get Started',
            highlight: false,
            features: [
                'Smart Product & Inventory Management',
                'Tours, Activities, Transfers, Hotels, Flights & Ferry',
                'Dynamic & Instant Price Quotation',
                'Advanced Multi-Product Quotation Engine',
                'Custom Trip & Itinerary Builder',
                'Interactive Digital Trip Links',
                'Professional PDF Proposal Generator',
                'Built-in Travel CRM',
                'Supplier & Contract Management Hub',
                'Email & Task Management',
                'Built-in Sales Pipeline in 1 Shared Board',
                'Unified Inbox for Customers, Suppliers & Teams',
                'Internal Team Chat & Collaboration',
                '1 Shared Mailbox · Up to 1 brand',
                'Webhooks: 3,000/month',
                'Up to 5 Quick Response Templates',
                'History Limit: 6 months · Storage: 25 GB',
                'Up to 3 users',
            ],
        },
        {
            name: 'Essencial',
            tagline: 'Advanced workflows and supplier tools for scaling teams',
            priceMonthly: 249,
            priceAnnually: 208,
            cta: 'Request Demo',
            highlight: false,
            features: [
                'Everything included in STARTER and:',
                'Shared Templates & Drive Uploads',
                'Automatic Route Calculation',
                'Open Integration API',
                'Payment Gateway',
                'Group Travel Management',
                'Supplier Financial Management',
                'Profitability Reports per Trip & Supplier',
                'Margin & Revenue Analytics Dashboard',
                'Advanced Task & Workflow Automation',
                'Personalized Travel Documents',
                'Dynamic Ticketing & Voucher Management',
                'Up to 3 Shared Mailboxes · Up to 1 brand',
                'Webhooks: 100,000/month',
                'Up to 25 Quick Response Templates',
                'History Limit: 2 years · Storage: 100 GB',
                'Up to 10 users',
            ],
        },
        {
            name: 'Premium',
            tagline: 'AI-powered pricing, multi-brand and enterprise analytics',
            priceMonthly: 589,
            priceAnnually: 491,
            cta: 'Request Demo',
            highlight: true,
            features: [
                'Everything included in ESSENCIAL and:',
                'AI-Powered Dynamic Pricing & Instant Calculation',
                'Smart Product Matching Based on Client Request',
                'AI-Powered Personalized Upgrade Suggestions',
                'API Integration with Flights, Hotels, GDS Systems',
                'Live Supplier & Reseller Connectivity',
                'Smart Finance Automation',
                'Enterprise Reporting & Business Intelligence',
                'Full Access Control & Team Permissions',
                'Priority Support & Dedicated Success Assistance',
                'Multi-Brand Management (Up to 3 brands)',
                'Custom Itinerary Design with Expert Support',
                'Tax & Accounting Integration',
                'Up to 9 Shared Mailboxes',
                'Unlimited Webhooks',
                'History Limit: 10 years · Storage: 200 GB',
                'Up to 50 users',
            ],
        },
        {
            name: 'Enterprise',
            tagline: 'Fully custom platform for large-scale travel operations',
            custom: true,
            cta: 'Contact Sales',
            highlight: false,
            features: [
                'Everything included in PREMIUM and:',
                'Fully Automated Booking System',
                'Private API Access',
                'AI-Powered Custom Trip Creation',
                'AI-Assisted Trip Structuring & Recommendations',
                'Unified Inbox for Customers, Suppliers & Teams',
                'Multi-Channel Communication Management',
                'Personalized Quotation Building (Multi-Supplier)',
                'Case-by-Case Workflow Management',
                'Smart Product Matching Based on Client Request',
                'Priority Handling for High-Value Requests',
                'Unlimited Mailboxes · Unlimited Brands',
                'Unlimited Webhooks · Unlimited Storage',
                'Unlimited users',
            ],
        },
    ],
    'all-products': [
        {
            name: 'Starter',
            tagline: 'Foundational tools for any business',
            priceMonthly: 35,
            priceAnnually: 28,
            cta: 'Get Started',
            highlight: false,
            features: [
                'Core system access',
                'Basic reporting',
                'Email support',
                'Up to 3 users',
            ],
        },
        {
            name: 'Professional',
            tagline: 'The choice for growing companies',
            priceMonthly: 75,
            priceAnnually: 60,
            cta: 'Request Demo',
            highlight: false,
            features: [
                'Advanced features',
                'Priority workflows',
                'Multi-user tools',
                'Up to 10 users',
            ],
        },
        {
            name: 'Premium',
            tagline: 'Complete automation & scale',
            priceMonthly: 110,
            priceAnnually: 88,
            cta: 'Request Demo',
            highlight: true,
            features: [
                'Full platform access',
                'Predictive analytics',
                'Unlimited users',
                '24/7 Priority support',
            ],
        },
        {
            name: 'Enterprise',
            tagline: 'Custom tailored platform',
            custom: true,
            cta: 'Contact Sales',
            highlight: false,
            features: [
                'White-label options',
                'Custom development',
                'Dedicated infrastructure',
                'Personalized training',
            ],
        },
    ],
};
